### ISSUE TITLE
感觉您这个架子里面的vue好像一个附属品

### ISSUE THREAD

**Issue by lgh06** [roshanca/starter-framework7#7]
如题 用得很牵强。。个人感觉。最近也在寻求/尝试vue和f7的整合。

**Comment by roshanca** [comment]
恩...有没有好的思路？最近打算重写一遍。

目前看来这里只用到了一点 vue 的数据绑定功能。本来想引入 vue-router 的，但跟 F7 的页面跳转机制又不符，很纠结。最好的方式是放弃 F7，UI 全用 vue 的方式来写，我看到已经有人在这么做了，但目前还比较薄弱。

**Comment by lgh06** [comment]
https://github.com/eteplus/vue-sui-demo 这个整合的实在是棒 有经验。sui和f7差不多 可以参照。

**Comment by roshanca** [comment]
ok，谢谢你，我回头好好看看。
